#spring.application.name=Service
# Database Configuration
#spring.datasource.url=jdbc:mariadb://localhost:3306/ccs
#spring.datasource.username=root
#spring.datasource.password=hema@2003
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA Configuration
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#not compulsary
# Optional: Format SQL in console
#spring.jpa.properties.hibernate.format_sql=true
# Database Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/ccs
spring.datasource.username=root
spring.datasource.password=hema@2003
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA Configuration
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional: Format SQL in console
spring.jpa.properties.hibernate.format_sql=true



#jdbc:database server://localhost:8080/database name
